### ISSUE TITLE
Evil graves

### ISSUE THREAD

**Issue by HacoKavanah** [ginsm/forgotten-graves#41]
We were casually playing with my friends on our server. One of them found an old grave of his, but instead of breaking, his inventory got entirely deleted and the grave refused to break. I put grave robbing on to see if this could help, but it only made it so that it also deleted my inventory???
forgottengraves-mc1.18.2-v2.5.0.jar

**Comment by HacoKavanah** [comment]
Found this in the log multiple times:

[14:05:46] [Server thread/ERROR]: Failed to handle packet net.minecraft.class_2885@57339178, suppressing error
java.lang.IndexOutOfBoundsException: toIndex = 53
	at Not Enough Crashes deobfuscated stack trace.(1.18.2+build.2) ~[?:?]
	at java.util.AbstractList.subListRangeCheck(AbstractList.java:507) ~[?:?]
	at java.util.AbstractList.subList(AbstractList.java:497) ~[?:?]
	at me.mgin.graves.block.GraveBase.useGrave(GraveBase.java:258) ~[forgottengraves-mc1.18.2-v2.5.0.jar:?]
	at me.mgin.graves.block.GraveBase.onUse(GraveBase.java:107) ~[forgottengraves-mc1.18.2-v2.5.0.jar:?]
	at net.minecraft.block.AbstractBlock$AbstractBlockState.onUse(AbstractBlock:939) ~[?:?]
	at net.minecraft.server.network.ServerPlayerInteractionManager.interactBlock(ServerPlayerInteractionManager:336) ~[?:?]
	at net.minecraft.server.network.ServerPlayNetworkHandler.onPlayerInteractBlock(ServerPlayNetworkHandler:1081) ~[?:?]
	at net.minecraft.network.packet.c2s.play.PlayerInteractBlockC2SPacket.apply(PlayerInteractBlockC2SPacket:30) ~[?:?]
	at net.minecraft.network.packet.c2s.play.PlayerInteractBlockC2SPacket.apply(PlayerInteractBlockC2SPacket:8) ~[?:?]
	at net.minecraft.network.NetworkThreadUtils.method_11072(NetworkThreadUtils:22) ~[?:?]
	at net.minecraft.server.ServerTask.run(ServerTask:18) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.executeTask(ThreadExecutor:157) ~[?:?]
	at net.minecraft.util.thread.ReentrantThreadExecutor.executeTask(ReentrantThreadExecutor:23) ~[?:?]
	at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer:808) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer:165) ~[client-intermediary.jar:?]
	at net.minecraft.util.thread.ThreadExecutor.runTask(ThreadExecutor:131) ~[?:?]
	at net.minecraft.server.MinecraftServer.runOneTask(MinecraftServer:790) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.runTask(MinecraftServer:784) ~[client-intermediary.jar:?]
	at net.minecraft.util.thread.ThreadExecutor.runTasks(ThreadExecutor:140) ~[?:?]
	at net.minecraft.server.MinecraftServer.runTasksTillTickEnd(MinecraftServer:769) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer:701) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer:273) ~[client-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]

**Comment by ginsm** [comment]
Hey there, that sounds like a nasty one.

I'm going to do some testing & mess around with the code and see if I can't resolve the issue. I believe it has to do with adding or removing a mod that adds extra slots after the particular grave has been placed.

Thanks for the report!

**Comment by ginsm** [comment]
Hey there, just an update: I've fixed the bug but I'm just doing some code clean up, working on resolving #40, etc.. but the fix should be released in the next couple days. Thanks again for the report!

**Comment by HacoKavanah** [comment]
Thank u so much! Final questions: will my friend get the "deleted" items back from the grave or are they lost forever?

**Comment by ginsm** [comment]
They should be able to retrieve the items that were already in the grave originally. Unfortunately, the items they had whilst trying to retrieve the grave are lost.

**Comment by HacoKavanah** [comment]
Hello! Did a new issue come up or have ya just been busy? The new version wasn't released in "the next couple of days" so that's why wondering lol :3 I hope this doesn't come off as rude...all the respect in the world for you!

**Comment by ginsm** [comment]
Howdy, I've been pretty busy at work lately so I haven't had the time to release it. That and I wanted to finish #40 before releasing (which more or less is now finished since last night).

I'm gonna go ahead and do my standard testing & then release it before I head to bed.

**Comment by ginsm** [comment]
Released a 1.18.1 and 1.18.2 version that should fix this -- let me know if you have any other issues, thanks!
